# Generated by Django 4.0.1 on 2022-01-19 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creation_time',
            new_name='create_at',
        ),
    ]
