# Generated by Django 4.0.1 on 2022-01-19 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0002_rename_creation_time_post_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commit',
            old_name='creation_time',
            new_name='create_at',
        ),
    ]
