# Generated by Django 4.0.1 on 2022-01-21 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postings', '0004_rename_commit_comment_like_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='follow_user_id',
            new_name='follow_user',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='followed_user_id',
            new_name='followed_user',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user_id',
            new_name='user',
        ),
    ]
